# Generated by Django 2.0 on 2017-12-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('address', models.CharField(help_text='unique address for the contract within the blockchain', max_length=200, primary_key=True, serialize=False, verbose_name='contract address')),
                ('status', models.CharField(choices=[('P', 'Pendent'), ('V', 'Validated')], help_text='informs about the validity of the contract', max_length=1, verbose_name='contract status')),
                ('date_creation', models.DateTimeField(verbose_name='date creation')),
                ('date_update', models.DateTimeField(verbose_name='date update')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=24, max_digits=34)),
                ('date_creation', models.DateTimeField(verbose_name='date creation')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Contract')),
            ],
        ),
    ]
