# Generated by Django 2.0 on 2017-12-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='votes',
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date update'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date creation'),
        ),
    ]
