# Generated by Django 2.0 on 2017-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20171230_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('P', 'Pendent'), ('V', 'Validated')], default='P', help_text='informs about the validity of the contract', max_length=1, verbose_name='contract status'),
        ),
    ]
