# Generated by Django 2.0 on 2017-12-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20171230_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(help_text='to be filled once utility contract reviewed, please see the coin name', max_length=128, null=True, verbose_name='coin name'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ticker',
            field=models.CharField(help_text='to be filled once utility contract reviewed, please see the coin code', max_length=10, null=True, verbose_name='coin code'),
        ),
    ]
